"""Publish a trained model (and optionally its dataset) to the Hugging Face Hub.

    hf auth login                      # once; or set HF_TOKEN
    python -m ml.push_to_hub --model extraction --repo YOUR_USER/gem-certificate-extractor
    python -m ml.push_to_hub --model risk --repo YOUR_USER/gem-bid-risk --with-dataset
    python -m ml.push_to_hub --model recommendation --repo YOUR_USER/gem-recommendation-writer --private

Writes a model card (README.md) filled with the model's own metrics.json, then uploads the model
directory. --with-dataset also publishes the generated JSONL splits as a dataset repo named
<repo>-data.
"""
import argparse
import json
import shutil
from pathlib import Path

from huggingface_hub import HfApi

from ml.common.io import DATA_DIR, MODELS_DIR

CARDS = Path(__file__).parent / "model_cards"
RISK_CODE = [Path(__file__).parent / "risk" / name for name in ("features.py", "infer.py")]


def _pct(value) -> str:
    return "-" if value is None else f"{value:.1%}"


def metrics_table(model: str, metrics: dict) -> str:
    if model == "extraction":
        test = metrics["test"]
        rows = ["| Field | Precision | Recall | F1 | Support |", "|---|---|---|---|---|"]
        rows += [f"| {label} | {_pct(m['precision'])} | {_pct(m['recall'])} | {_pct(m['f1'])} | {m['support']} |"
                 for label, m in test["per_label"].items()]
        micro = test["micro"]
        rows.append(f"| **All (micro)** | {_pct(micro['precision'])} | {_pct(micro['recall'])} | **{_pct(micro['f1'])}** | {micro['support']} |")
        return "Entity-level, exact span match:\n\n" + "\n".join(rows)
    if model == "risk":
        m, r = metrics["model_on_observed"], metrics["rule_engine_on_observed"]
        rows = ["| | Accuracy | Macro-F1 |", "|---|---|---|",
                f"| This model | **{_pct(m['accuracy'])}** | **{_pct(m['macro_f1'])}** |",
                f"| Rule engine on the same observations | {_pct(r['accuracy'])} | {_pct(r['macro_f1'])} |"]
        per_class = ["| Class | Precision | Recall | Support |", "|---|---|---|---|"]
        per_class += [f"| {c} | {_pct(v['precision'])} | {_pct(v['recall'])} | {v['support']} |" for c, v in m["per_class"].items()]
        return "Against the verdict on complete information:\n\n" + "\n".join(rows) + "\n\n" + "\n".join(per_class)
    test = metrics["test"]
    return "\n".join([
        "| Metric | Value |", "|---|---|",
        f"| Correct verdict | {_pct(test['verdict_accuracy'])} |",
        f"| Findings mentioned (recall) | {_pct(test['finding_recall'])} |",
        f"| Outputs inventing a finding | {_pct(test['invented_rate'])} |",
        f"| Carries the advisory label | {_pct(test['advisory_label_rate'])} |",
        f"| Examples graded | {test['examples']} |",
    ])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True, choices=["extraction", "risk", "recommendation"])
    parser.add_argument("--repo", required=True, help="e.g. your-username/gem-bid-risk")
    parser.add_argument("--model-dir", default=None)
    parser.add_argument("--private", action="store_true")
    parser.add_argument("--with-dataset", action="store_true")
    args = parser.parse_args()

    model_dir = Path(args.model_dir or MODELS_DIR / args.model)
    metrics = json.loads((model_dir / "metrics.json").read_text())
    data_dir = DATA_DIR / args.model
    counts = {s: sum(1 for _ in (data_dir / f"{s}.jsonl").open(encoding="utf-8"))
              for s in ("train", "validation", "test") if (data_dir / f"{s}.jsonl").exists()}
    dataset_note = (
        f"Generated by `ml/{args.model}/generate.py`: "
        + ", ".join(f"{n:,} {s}" for s, n in counts.items()) + " examples."
        if counts else f"Generated by `ml/{args.model}/generate.py`."
    )
    if args.with_dataset:
        dataset_note += f" Published as [`{args.repo}-data`](https://huggingface.co/datasets/{args.repo}-data)."

    card = (CARDS / f"{args.model}.md").read_text(encoding="utf-8")
    card = card.replace("{metrics_table}", metrics_table(args.model, metrics))
    card = card.replace("{dataset_note}", dataset_note).replace("{repo_id}", args.repo)
    (model_dir / "README.md").write_text(card, encoding="utf-8")
    if args.model == "risk":
        for path in RISK_CODE:
            shutil.copy(path, model_dir / path.name)

    api = HfApi()
    api.create_repo(args.repo, repo_type="model", private=args.private, exist_ok=True)
    api.upload_folder(repo_id=args.repo, folder_path=str(model_dir), ignore_patterns=["checkpoints/*"],
                      commit_message=f"Upload {args.model} model")
    print(f"model: https://huggingface.co/{args.repo}")

    if args.with_dataset:
        dataset_repo = f"{args.repo}-data"
        api.create_repo(dataset_repo, repo_type="dataset", private=args.private, exist_ok=True)
        api.upload_folder(repo_id=dataset_repo, repo_type="dataset", folder_path=str(data_dir),
                          commit_message=f"Upload synthetic {args.model} dataset")
        print(f"dataset: https://huggingface.co/datasets/{dataset_repo}")


if __name__ == "__main__":
    main()
